import './globals.css'
import { Inter } from 'next/font/google'
import favicon from "./favicon.ico";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
