export const genreCodes = [
  {
    id: 243,
    name: "4-Koma",
    slug: "4-koma",
    comic_count: 1561,
  },
  {
    id: 244,
    name: "Action",
    slug: "action",
    comic_count: 13978,
  },
  {
    id: 279,
    name: "Adaptation",
    slug: "adaptation",
    comic_count: 5572,
  },
  {
    id: 2,
    name: "Adult",
    slug: "adult",
    comic_count: 10,
  },
  {
    id: 245,
    name: "Adventure",
    slug: "adventure",
    comic_count: 8465,
  },
  {
    id: 294,
    name: "Aliens",
    slug: "aliens",
    comic_count: 718,
  },
  {
    id: 295,
    name: "Animals",
    slug: "animals",
    comic_count: 2108,
  },
  {
    id: 280,
    name: "Anthology",
    slug: "anthology",
    comic_count: 1888,
  },
  {
    id: 246,
    name: "Award Winning",
    slug: "award-winning",
    comic_count: 790,
  },
  {
    id: 247,
    name: "Comedy",
    slug: "comedy",
    comic_count: 26286,
  },
  {
    id: 248,
    name: "Cooking",
    slug: "cooking",
    comic_count: 930,
  },
  {
    id: 288,
    name: "Crime",
    slug: "crime",
    comic_count: 1421,
  },
  {
    id: 296,
    name: "Crossdressing",
    slug: "crossdressing",
    comic_count: 1290,
  },
  {
    id: 298,
    name: "Delinquents",
    slug: "delinquents",
    comic_count: 1341,
  },
  {
    id: 297,
    name: "Demons",
    slug: "demons",
    comic_count: 2005,
  },
  {
    id: 249,
    name: "Doujinshi",
    slug: "doujinshi",
    comic_count: 6738,
  },
  {
    id: 250,
    name: "Drama",
    slug: "drama",
    comic_count: 22658,
  },
  {
    id: 251,
    name: "Ecchi",
    slug: "ecchi",
    comic_count: 13225,
  },
  {
    id: 285,
    name: "Fan Colored",
    slug: "fan-colored",
    comic_count: 87,
  },
  {
    id: 252,
    name: "Fantasy",
    slug: "fantasy",
    comic_count: 14778,
  },
  {
    id: 282,
    name: "Full Color",
    slug: "full-color",
    comic_count: 9976,
  },
  {
    id: 1,
    name: "Gender Bender",
    slug: "gender-bender",
    comic_count: 8,
  },
  {
    id: 299,
    name: "Genderswap",
    slug: "genderswap",
    comic_count: 826,
  },
  {
    id: 300,
    name: "Ghosts",
    slug: "ghosts",
    comic_count: 903,
  },
  {
    id: 286,
    name: "Gore",
    slug: "gore",
    comic_count: 2147,
  },
  {
    id: 253,
    name: "Gyaru",
    slug: "gyaru",
    comic_count: 336,
  },
  {
    id: 254,
    name: "Harem",
    slug: "harem",
    comic_count: 2195,
  },
  {
    id: 255,
    name: "Historical",
    slug: "historical",
    comic_count: 4652,
  },
  {
    id: 256,
    name: "Horror",
    slug: "horror",
    comic_count: 3270,
  },
  {
    id: 320,
    name: "Incest",
    slug: "incest",
    comic_count: 499,
  },
  {
    id: 278,
    name: "Isekai",
    slug: "isekai",
    comic_count: 2453,
  },
  {
    id: 302,
    name: "Loli",
    slug: "loli",
    comic_count: 434,
  },
  {
    id: 274,
    name: "Long Strip",
    slug: "long-strip",
    comic_count: 10319,
  },
  {
    id: 321,
    name: "Mafia",
    slug: "mafia",
    comic_count: 675,
  },
  {
    id: 303,
    name: "Magic",
    slug: "magic",
    comic_count: 3282,
  },
  {
    id: 289,
    name: "Magical Girls",
    slug: "magical-girls",
    comic_count: 318,
  },
  {
    id: 257,
    name: "Martial Arts",
    slug: "martial-arts",
    comic_count: 2919,
  },
  {
    id: 3,
    name: "Mature",
    slug: "mature",
    comic_count: 28,
  },
  {
    id: 258,
    name: "Mecha",
    slug: "mecha",
    comic_count: 1127,
  },
  {
    id: 259,
    name: "Medical",
    slug: "medical",
    comic_count: 424,
  },
  {
    id: 304,
    name: "Military",
    slug: "military",
    comic_count: 1640,
  },
  {
    id: 301,
    name: "Monster Girls",
    slug: "monster-girls",
    comic_count: 889,
  },
  {
    id: 305,
    name: "Monsters",
    slug: "monsters",
    comic_count: 2863,
  },
  {
    id: 260,
    name: "Music",
    slug: "music",
    comic_count: 741,
  },
  {
    id: 261,
    name: "Mystery",
    slug: "mystery",
    comic_count: 4994,
  },
  {
    id: 306,
    name: "Ninja",
    slug: "ninja",
    comic_count: 326,
  },
  {
    id: 307,
    name: "Office Workers",
    slug: "office-workers",
    comic_count: 1805,
  },
  {
    id: 284,
    name: "Official Colored",
    slug: "official-colored",
    comic_count: 171,
  },
  {
    id: 262,
    name: "Oneshot",
    slug: "oneshot",
    comic_count: 10917,
  },
  {
    id: 290,
    name: "Philosophical",
    slug: "philosophical",
    comic_count: 1005,
  },
  {
    id: 308,
    name: "Police",
    slug: "police",
    comic_count: 915,
  },
  {
    id: 309,
    name: "Post-Apocalyptic",
    slug: "post-apocalyptic",
    comic_count: 614,
  },
  {
    id: 263,
    name: "Psychological",
    slug: "psychological",
    comic_count: 5407,
  },
  {
    id: 310,
    name: "Reincarnation",
    slug: "reincarnation",
    comic_count: 2061,
  },
  {
    id: 311,
    name: "Reverse Harem",
    slug: "reverse-harem",
    comic_count: 487,
  },
  {
    id: 264,
    name: "Romance",
    slug: "romance",
    comic_count: 28659,
  },
  {
    id: 312,
    name: "Samurai",
    slug: "samurai",
    comic_count: 527,
  },
  {
    id: 265,
    name: "School Life",
    slug: "school-life",
    comic_count: 14450,
  },
  {
    id: 266,
    name: "Sci-Fi",
    slug: "sci-fi",
    comic_count: 3716,
  },
  {
    id: 287,
    name: "Sexual Violence",
    slug: "sexual-violence",
    comic_count: 1561,
  },
  {
    id: 313,
    name: "Shota",
    slug: "shota",
    comic_count: 262,
  },
  {
    id: 267,
    name: "Shoujo Ai",
    slug: "shoujo-ai",
    comic_count: 10,
  },
  {
    id: 268,
    name: "Shounen Ai",
    slug: "shounen-ai",
    comic_count: 34,
  },
  {
    id: 269,
    name: "Slice of Life",
    slug: "slice-of-life",
    comic_count: 16438,
  },
  {
    id: 270,
    name: "Smut",
    slug: "smut",
    comic_count: 11,
  },
  {
    id: 271,
    name: "Sports",
    slug: "sports",
    comic_count: 2182,
  },
  {
    id: 291,
    name: "Superhero",
    slug: "superhero",
    comic_count: 399,
  },
  {
    id: 272,
    name: "Supernatural",
    slug: "supernatural",
    comic_count: 10237,
  },
  {
    id: 314,
    name: "Survival",
    slug: "survival",
    comic_count: 2034,
  },
  {
    id: 292,
    name: "Thriller",
    slug: "thriller",
    comic_count: 2239,
  },
  {
    id: 315,
    name: "Time Travel",
    slug: "time-travel",
    comic_count: 957,
  },
  {
    id: 317,
    name: "Traditional Games",
    slug: "traditional-games",
    comic_count: 258,
  },
  {
    id: 273,
    name: "Tragedy",
    slug: "tragedy",
    comic_count: 4512,
  },
  {
    id: 283,
    name: "User Created",
    slug: "user-created",
    comic_count: 712,
  },
  {
    id: 316,
    name: "Vampires",
    slug: "vampires",
    comic_count: 711,
  },
  {
    id: 277,
    name: "Video Games",
    slug: "video-games",
    comic_count: 1308,
  },
  {
    id: 322,
    name: "Villainess",
    slug: "villainess",
    comic_count: 525,
  },
  {
    id: 318,
    name: "Virtual Reality",
    slug: "virtual-reality",
    comic_count: 234,
  },
  {
    id: 281,
    name: "Web Comic",
    slug: "web-comic",
    comic_count: 11532,
  },
  {
    id: 293,
    name: "Wuxia",
    slug: "wuxia",
    comic_count: 420,
  },
  {
    id: 275,
    name: "Yaoi",
    slug: "yaoi",
    comic_count: 10175,
  },
  {
    id: 276,
    name: "Yuri",
    slug: "yuri",
    comic_count: 4590,
  },
  {
    id: 319,
    name: "Zombies",
    slug: "zombies",
    comic_count: 348,
  },
];
